name: Upbit Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Python 설치
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: 패키지 설치
        run: pip install pyupbit

      - name: 실행
        env:
          UPBIT_ACCESS_KEY: ${{ secrets.UPBIT_ACCESS_KEY }}
          UPBIT_SECRET_KEY: ${{ secrets.UPBIT_SECRET_KEY }}
        run: python test.py
