name: Live ETH Bot

on:
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    env:
      KRAKEN_KEY: ${{ secrets.KRAKEN_KEY }}
      KRAKEN_SECRET: ${{ secrets.KRAKEN_SECRET }}
      TOKEN: ${{ secrets.TOKEN }}
      CHAT_ID: ${{ secrets.CHAT_ID }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: pip install -r requirements.txt

      - name: Run Bot
        run: python live_eth_bot.py
