name: Live ETH BTC Bot

on:
  workflow_dispatch:

  schedule:
    - cron: "0 * * * *"

permissions:
  contents: write

jobs:
  run-bots:
    runs-on: ubuntu-latest

    env:
      KRAKEN_KEY: ${{ secrets.KRAKEN_KEY }}
      KRAKEN_SECRET: ${{ secrets.KRAKEN_SECRET }}

      TOKEN: ${{ secrets.TOKEN }}
      CHAT_ID: ${{ secrets.CHAT_ID }}

    steps:
      # ==========================
      # Checkout Repo
      # ==========================

      - uses: actions/checkout@v4

      # ==========================
      # Python
      # ==========================

      - uses: actions/setup-python@v5

        with:
          python-version: "3.11"

      # ==========================
      # Install Packages
      # ==========================

      - name: Install Packages

        run: |
          pip install -r requirements.txt

      # ==========================
      # Run ETH Bot
      # ==========================

      - name: Run ETH Bot

        run: |
          python live_eth_bot.py

      # ==========================
      # Run BTC Bot
      # ==========================

      - name: Run BTC Bot

        run: |
          python live_btc_bot.py

      # ==========================
      # Save Trade Logs
      # ==========================

      - name: Save Trade Logs

        run: |

          git config user.name "github-actions"

          git config user.email "github-actions@github.com"

          git add trade_log.csv btc_trade_log.csv || true

          git commit -m "Update trade logs" || echo "No changes to commit"

          git push
