name: Upbit Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Packages
        run: pip install pyupbit requests

      - name: Run Test
        env:
          UPBIT_ACCESS_KEY: ${{ secrets.UPBIT_ACCESS_KEY }}
          UPBIT_SECRET_KEY: ${{ secrets.UPBIT_SECRET_KEY }}
        run: python test.py
